repos:
  - repo: local
    hooks:
      - id: autoflake
        name: Remove unused variables and imports
        entry: bash -c 'autoflake "$@"; git add -u' --
        language: python
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]
        files: \.py$
      - id: isort
        name: Sorting import statements
        entry: bash -c 'isort "$@"; git add -u' --
        language: python
        args: ["--filter-files"]
        files: \.py$
      - id: black-jupyter
        name: Black Python code formatting
        entry: bash -c 'black "$@"; git add -u' --
        language: python
        types: [python]
      - id: flake8
        name: Flake8 linting
        entry: bash -c 'flake8 "$@"'
        language: python
        types: [python]
        args: # arguments to configure flake8
          # check for Python syntax errors or undefined names
          - "--count"
          - "--select=E9,F63,F7,F82"
          - "--show-source"
          - "--statistics"
          - "--max-complexity=10"