name: environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - selenium
  - arrow
  - pdfminer
  - beautifulsoup4
  - matplotlib
  - python-dotenv
  - jupyterlab
  - jupytext
  - matplotlib
  - gspread
  - pip
  - pip:
    - get-gecko-driver
