# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - '**'
  #pull_request:
  #  branches:
  #    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install python3.9-venv and firefox
      run: sudo apt-get install python3.9-venv firefox
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.0
    #- name: Lint with flake8
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install latest gecko driver
      run: |
        pip install get-gecko-driver
        get-gecko-driver --download-latest --extract    
    - name: Poetry install
      run: |
        poetry install
    #- name: Test with pytest
    #  env:
    #    KITCHENER_UTILITIES_USER: ${{ secrets.KITCHENER_UTILITIES_USER }}
    #    KITCHENER_UTILITIES_PASSWORD: ${{ secrets.KITCHENER_UTILITIES_PASSWORD }}
    #  run: |
    #    poetry run pytest
    - name: Send email
      uses: dawidd6/action-send-mail@v3.5.0
      with:
        server_address: smtp.sendgrid.net
        server_port: 465
        username: apikey
        password: ${{ secrets.SENDGRID_API_KEY }}
        subject: utility bill scraper
        to: Ryan Fobel <ryan@fobel.net>
        from: Ryan Fobel <ryan@fobel.net>
        body: "Test email from github actions"
