name: Update Kitchener-Wilmot Hydro

on:
  schedule:
    # Run everyday at midnight
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install python3.9-venv and firefox
      run: sudo apt-get install python3.9-venv firefox
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.2.0
    - name: Install latest gecko driver
      run: |
        pip install get-gecko-driver
        get-gecko-driver --download-latest --extract    
    - name: Poetry install
      run: |
        poetry install
    - name: Update Kitchener Utilities
      env:
        USER: ${{ secrets.KITCHENER_UTILITIES_USER }}
        PASSWORD: ${{ secrets.KITCHENER_UTILITIES_PASSWORD }}
        DATA_PATH: ${{ secrets.DATA_PATH }}
        GOOGLE_SA_CREDENTIALS: ${{ secrets.GOOGLE_SA_CREDENTIALS }}
      run: |
        poetry run ubs --utility-name "Kitchener Utilities" update > ubs.log
        echo "DOWNLOADED="`cat ubs.log | grep Downloaded | sed 's/^Downloaded \(.*\) new statements$/\1/'` > DOWNLOADED
        cat DOWNLOADED
        cat DOWNLOADED > $GITHUB_ENV
    - name: Publish notebooks to html
      if: env.DOWNLOADED > 0
      env:
        KITCHENER_UTILITIES_USER: ${{ secrets.KITCHENER_UTILITIES_USER }}
        KITCHENER_UTILITIES_PASSWORD: ${{ secrets.KITCHENER_UTILITIES_PASSWORD }}
        DATA_PATH: ${{ secrets.DATA_PATH }}
        GOOGLE_SA_CREDENTIALS: ${{ secrets.GOOGLE_SA_CREDENTIALS }}
      run: |
        poetry run jupyter nbconvert --execute --to html notebooks/canada/on/kitchener_utilities.ipynb
    - name: Send email
      if: env.DOWNLOADED > 0
      uses: dawidd6/action-send-mail@v3.5.0
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ryan@fobel.net
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: ${{ env.DOWNLOADED }} new Kitchener Utilities statement(s)
        to: Ryan Fobel <ryan@fobel.net>
        from: Ryan Fobel <ryan@fobel.net>
        body: ${{ env.DOWNLOADED }} new statement(s) downloaded.
        attachments: notebooks/canada/on/kitchener_utilities.html
